name: fastai2
channels:
- fastai
- pytorch
- defaults
dependencies:
- jupyter
- pytorch>=1.3.0
- torchvision>=0.5
- matplotlib
- pandas
- requests
- pyyaml
- fastprogress>=0.1.22
- pillow
- python>=3.6
- pip
- scikit-learn
- scipy
- spacy
- pip:
  - voila
  - git+https://github.com/fastai/fastcore.git@master
  - git+https://github.com/fastai/fastai2.git@master
  - nbdev
  - graphviz
